### ISSUE TITLE
Feature request: Add an option to ignore config keys that gorilla doesn't recognize

### ISSUE THREAD

**Issue by OwenEdwards** [apsking/gorilla#128]
I'm trying to set up `gorilla-build` to build my Tampermonkey script, and I have the build process configured using [npm's package.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-json) format. This already has most of the config values I want (`name`, `description`, `version`, `author`, etc), but it also has other info such as `copyright`, `license`, `homepage`, `scripts`, and `repository`.

I don't want to have to duplicate the parts of the config that are in `package.json` into a separate config file for gorilla, and risk information such as the `version` number getting out of sync, so I was thinking that if gorilla could accept an option to just ignore what it calls "config key(s)" that it doesn't recognize, then it would work with a `package.json` file but its default behavior of throwing an error if there are keys it doesn't recognize wouldn't change.

Let me know if this makes sense. Thanks!

**Comment by apsking** [comment]
Hi! This sounds like a cool idea. I want to confirm my understanding. It sounds like there are two separate asks in here:
* Have `gorilla` read key-values from the `package.json`. Specifically, the common ones that are also in the `npm` specification.
* Allow `gorilla` to read arbitrary keys defined by the user

Does that cover it?

**Comment by apsking** [comment]
Check out `v0.0.12`, which reads some values from the `package.json` file. That should address your issue!
